---
- name: Copy files using owner, group and permissions
  hosts: localhost

  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./files/testfile
        dest: /tmp/testfile
        decrypt: yes
        owner: smv87815
        group: muzcee
        mode: '0644'
      delegate_to: rancher
