---
- name: Copy files using owner, group and permissions
  hosts: all

  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./files/testfile
        dest: /tmp/testfile
        decrypt: yes
        owner: smv87815
        group: smv87815
        mode: '0644'
