---
- name: shutdown server
  hosts: localhost
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure machine is powered on
      community.general.ipmi_power:
        name: 192.168.1.201
        user: root
        password: REMEMBERTHIS
        state: 'on'
      delegate_to: ubuntu1
