---
- name: Proxmox playbook
  hosts: pve1
  user: root

  tasks:
  - name: Get all vm ids
    ansible.builtin.shell:
      cmd: /usr/sbin/qm list
    register: list

  - name: Print all vm ids
    ansible.builtin.debug:
      var: list.stdout_lines

